export const cadencePatterns = [
    { type: "Major", pattern: [[62, 65, 69, 72], [62, 65, 67, 71], [60, 64, 67, 71]] },
    { type: "Minor", pattern: [[62, 65, 68, 72], [62, 65, 67, 71], [60, 63, 67, 72]] },
    { type: "Major Chromatic", pattern: [[2, 5, 9, 12], [2, 5, 7, 11], [0, 4, 7, 11]] },
    { type: "Minor Chromatic", pattern: [[2, 5, 8, 12], [2, 5, 7, 11], [0, 3, 7, 12]] }
]

export const scalePatterns = [
    { type: "Chromatic", pattern: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1] },
    { type: "Major", pattern: [2, 2, 1, 2, 2, 2, 1] },
    { type: "Minor", pattern: [2, 1, 2, 2, 1, 2, 2] },
    { type: "Harm Min", pattern: [2, 1, 2, 2, 1, 3, 1] },
    { type: "Mel Min", pattern: [2, 1, 2, 2, 2, 2, 1] },
    { type: "Dor", pattern: [2, 1, 2, 2, 2, 1, 2] },
    { type: "Mixo", pattern: [2, 2, 1, 2, 2, 1, 2] },
    { type: "Ahava Raba", pattern: [3, 2, 2, 3, 2] },
    { type: "Altered", pattern: [1, 2, 1, 2, 2, 2, 2] },
    { type: "Lyd Dom", pattern: [2, 2, 2, 1, 2, 2, 1] },
    { type: "Locrian", pattern: [1, 2, 2, 1, 2, 2, 2] }
]

export const instruments = [
    {
        instrumentName: "Piano",
        instrumentSounds: [
            { midiNumber: 36, noteName: "C2", filePath: "/audio/piano/36.m4a" },
            { midiNumber: 37, noteName: "C#/Db2", filePath: "/audio/piano/37.m4a" },
            { midiNumber: 38, noteName: "D2", filePath: "/audio/piano/38.m4a" },
            { midiNumber: 39, noteName: "D#/Eb2", filePath: "/audio/piano/39.m4a" },
            { midiNumber: 40, noteName: "E2", filePath: "/audio/piano/40.m4a" },
            { midiNumber: 41, noteName: "F2", filePath: "/audio/piano/41.m4a" },
            { midiNumber: 42, noteName: "F#/Gb2", filePath: "/audio/piano/42.m4a" },
            { midiNumber: 43, noteName: "G2", filePath: "/audio/piano/43.m4a" },
            { midiNumber: 44, noteName: "G#/Ab2", filePath: "/audio/piano/44.m4a" },
            { midiNumber: 45, noteName: "A2", filePath: "/audio/piano/45.m4a" },
            { midiNumber: 46, noteName: "A#/Bb2", filePath: "/audio/piano/46.m4a" },
            { midiNumber: 47, noteName: "B2", filePath: "/audio/piano/47.m4a" },
            { midiNumber: 48, noteName: "C3", filePath: "/audio/piano/48.m4a" },
            { midiNumber: 49, noteName: "C#/Db3", filePath: "/audio/piano/49.m4a" },
            { midiNumber: 50, noteName: "D3", filePath: "/audio/piano/50.m4a" },
            { midiNumber: 51, noteName: "D#/Eb3", filePath: "/audio/piano/51.m4a" },
            { midiNumber: 52, noteName: "E3", filePath: "/audio/piano/52.m4a" },
            { midiNumber: 53, noteName: "F3", filePath: "/audio/piano/53.m4a" },
            { midiNumber: 54, noteName: "F#/Gb3", filePath: "/audio/piano/54.m4a" },
            { midiNumber: 55, noteName: "G3", filePath: "/audio/piano/55.m4a" },
            { midiNumber: 56, noteName: "G#/Ab3", filePath: "/audio/piano/56.m4a" },
            { midiNumber: 57, noteName: "A3", filePath: "/audio/piano/57.m4a" },
            { midiNumber: 58, noteName: "A#/Bb3", filePath: "/audio/piano/58.m4a" },
            { midiNumber: 59, noteName: "B3", filePath: "/audio/piano/59.m4a" },
            { midiNumber: 60, noteName: "C4", filePath: "/audio/piano/60.m4a" },
            { midiNumber: 61, noteName: "C#/Db4", filePath: "/audio/piano/61.m4a" },
            { midiNumber: 62, noteName: "D4", filePath: "/audio/piano/62.m4a" },
            { midiNumber: 63, noteName: "D#/Eb4", filePath: "/audio/piano/63.m4a" },
            { midiNumber: 64, noteName: "E4", filePath: "/audio/piano/64.m4a" },
            { midiNumber: 65, noteName: "F4", filePath: "/audio/piano/65.m4a" },
            { midiNumber: 66, noteName: "F#/Gb4", filePath: "/audio/piano/66.m4a" },
            { midiNumber: 67, noteName: "G4", filePath: "/audio/piano/67.m4a" },
            { midiNumber: 68, noteName: "G#/Ab4", filePath: "/audio/piano/68.m4a" },
            { midiNumber: 69, noteName: "A4", filePath: "/audio/piano/69.m4a" },
            { midiNumber: 70, noteName: "A#/Bb4", filePath: "/audio/piano/70.m4a" },
            { midiNumber: 71, noteName: "B4", filePath: "/audio/piano/71.m4a" },
            { midiNumber: 72, noteName: "C5", filePath: "/audio/piano/72.m4a" },
            { midiNumber: 73, noteName: "C#/Db5", filePath: "/audio/piano/73.m4a" },
            { midiNumber: 74, noteName: "D5", filePath: "/audio/piano/74.m4a" },
            { midiNumber: 75, noteName: "D#/Eb5", filePath: "/audio/piano/75.m4a" },
            { midiNumber: 76, noteName: "E5", filePath: "/audio/piano/76.m4a" },
            { midiNumber: 77, noteName: "F5", filePath: "/audio/piano/77.m4a" },
            { midiNumber: 78, noteName: "F#/Gb5", filePath: "/audio/piano/78.m4a" },
            { midiNumber: 79, noteName: "G5", filePath: "/audio/piano/79.m4a" },
            { midiNumber: 80, noteName: "G#/Ab5", filePath: "/audio/piano/80.m4a" },
            { midiNumber: 81, noteName: "A5", filePath: "/audio/piano/81.m4a" },
            { midiNumber: 82, noteName: "A#/Bb5", filePath: "/audio/piano/82.m4a" },
            { midiNumber: 83, noteName: "B5", filePath: "/audio/piano/83.m4a" },
            { midiNumber: 84, noteName: "C6", filePath: "/audio/piano/84.m4a" },
            { midiNumber: 85, noteName: "C#/Db6", filePath: "/audio/piano/85.m4a" },
            { midiNumber: 86, noteName: "D6", filePath: "/audio/piano/86.m4a" },
            { midiNumber: 87, noteName: "D#/Eb6", filePath: "/audio/piano/87.m4a" },
            { midiNumber: 88, noteName: "E6", filePath: "/audio/piano/88.m4a" },
            { midiNumber: 89, noteName: "F6", filePath: "/audio/piano/89.m4a" },
            { midiNumber: 90, noteName: "F#/Gb6", filePath: "/audio/piano/90.m4a" },
            { midiNumber: 91, noteName: "G6", filePath: "/audio/piano/91.m4a" },
            { midiNumber: 92, noteName: "G#/Ab6", filePath: "/audio/piano/92.m4a" },
            { midiNumber: 93, noteName: "A6", filePath: "/audio/piano/93.m4a" },
            { midiNumber: 94, noteName: "A#/Bb6", filePath: "/audio/piano/94.m4a" },
            { midiNumber: 95, noteName: "B6", filePath: "/audio/piano/95.m4a" },
            { midiNumber: 96, noteName: "C7", filePath: "/audio/piano/96.m4a" },
            { midiNumber: 97, noteName: "C#/Db7", filePath: "/audio/piano/97.m4a" },
            { midiNumber: 98, noteName: "D7", filePath: "/audio/piano/98.m4a" },
            { midiNumber: 99, noteName: "D#/Eb7", filePath: "/audio/piano/99.m4a" },
            { midiNumber: 100, noteName: "E7", filePath: "/audio/piano/100.m4a" },
            { midiNumber: 101, noteName: "F7", filePath: "/audio/piano/101.m4a" },
            { midiNumber: 102, noteName: "F#/Gb7", filePath: "/audio/piano/102.m4a" },
            { midiNumber: 103, noteName: "G7", filePath: "/audio/piano/103.m4a" }
        ]
    },
    {
        instrumentName: "Rhodes",
        instrumentSounds: [
            { midiNumber: 36, noteName: "C2", filePath: "/audio/rhodes/36.m4a" },
            { midiNumber: 37, noteName: "C#/Db2", filePath: "/audio/rhodes/37.m4a" },
            { midiNumber: 38, noteName: "D2", filePath: "/audio/rhodes/38.m4a" },
            { midiNumber: 39, noteName: "D#/Eb2", filePath: "/audio/rhodes/39.m4a" },
            { midiNumber: 40, noteName: "E2", filePath: "/audio/rhodes/40.m4a" },
            { midiNumber: 41, noteName: "F2", filePath: "/audio/rhodes/41.m4a" },
            { midiNumber: 42, noteName: "F#/Gb2", filePath: "/audio/rhodes/42.m4a" },
            { midiNumber: 43, noteName: "G2", filePath: "/audio/rhodes/43.m4a" },
            { midiNumber: 44, noteName: "G#/Ab2", filePath: "/audio/rhodes/44.m4a" },
            { midiNumber: 45, noteName: "A2", filePath: "/audio/rhodes/45.m4a" },
            { midiNumber: 46, noteName: "A#/Bb2", filePath: "/audio/rhodes/46.m4a" },
            { midiNumber: 47, noteName: "B2", filePath: "/audio/rhodes/47.m4a" },
            { midiNumber: 48, noteName: "C3", filePath: "/audio/rhodes/48.m4a" },
            { midiNumber: 49, noteName: "C#/Db3", filePath: "/audio/rhodes/49.m4a" },
            { midiNumber: 50, noteName: "D3", filePath: "/audio/rhodes/50.m4a" },
            { midiNumber: 51, noteName: "D#/Eb3", filePath: "/audio/rhodes/51.m4a" },
            { midiNumber: 52, noteName: "E3", filePath: "/audio/rhodes/52.m4a" },
            { midiNumber: 53, noteName: "F3", filePath: "/audio/rhodes/53.m4a" },
            { midiNumber: 54, noteName: "F#/Gb3", filePath: "/audio/rhodes/54.m4a" },
            { midiNumber: 55, noteName: "G3", filePath: "/audio/rhodes/55.m4a" },
            { midiNumber: 56, noteName: "G#/Ab3", filePath: "/audio/rhodes/56.m4a" },
            { midiNumber: 57, noteName: "A3", filePath: "/audio/rhodes/57.m4a" },
            { midiNumber: 58, noteName: "A#/Bb3", filePath: "/audio/rhodes/58.m4a" },
            { midiNumber: 59, noteName: "B3", filePath: "/audio/rhodes/59.m4a" },
            { midiNumber: 60, noteName: "C4", filePath: "/audio/rhodes/60.m4a" },
            { midiNumber: 61, noteName: "C#/Db4", filePath: "/audio/rhodes/61.m4a" },
            { midiNumber: 62, noteName: "D4", filePath: "/audio/rhodes/62.m4a" },
            { midiNumber: 63, noteName: "D#/Eb4", filePath: "/audio/rhodes/63.m4a" },
            { midiNumber: 64, noteName: "E4", filePath: "/audio/rhodes/64.m4a" },
            { midiNumber: 65, noteName: "F4", filePath: "/audio/rhodes/65.m4a" },
            { midiNumber: 66, noteName: "F#/Gb4", filePath: "/audio/rhodes/66.m4a" },
            { midiNumber: 67, noteName: "G4", filePath: "/audio/rhodes/67.m4a" },
            { midiNumber: 68, noteName: "G#/Ab4", filePath: "/audio/rhodes/68.m4a" },
            { midiNumber: 69, noteName: "A4", filePath: "/audio/rhodes/69.m4a" },
            { midiNumber: 70, noteName: "A#/Bb4", filePath: "/audio/rhodes/70.m4a" },
            { midiNumber: 71, noteName: "B4", filePath: "/audio/rhodes/71.m4a" },
            { midiNumber: 72, noteName: "C5", filePath: "/audio/rhodes/72.m4a" },
            { midiNumber: 73, noteName: "C#/Db5", filePath: "/audio/rhodes/73.m4a" },
            { midiNumber: 74, noteName: "D5", filePath: "/audio/rhodes/74.m4a" },
            { midiNumber: 75, noteName: "D#/Eb5", filePath: "/audio/rhodes/75.m4a" },
            { midiNumber: 76, noteName: "E5", filePath: "/audio/rhodes/76.m4a" },
            { midiNumber: 77, noteName: "F5", filePath: "/audio/rhodes/77.m4a" },
            { midiNumber: 78, noteName: "F#/Gb5", filePath: "/audio/rhodes/78.m4a" },
            { midiNumber: 79, noteName: "G5", filePath: "/audio/rhodes/79.m4a" },
            { midiNumber: 80, noteName: "G#/Ab5", filePath: "/audio/rhodes/80.m4a" },
            { midiNumber: 81, noteName: "A5", filePath: "/audio/rhodes/81.m4a" },
            { midiNumber: 82, noteName: "A#/Bb5", filePath: "/audio/rhodes/82.m4a" },
            { midiNumber: 83, noteName: "B5", filePath: "/audio/rhodes/83.m4a" },
            { midiNumber: 84, noteName: "C6", filePath: "/audio/rhodes/84.m4a" },
            { midiNumber: 85, noteName: "C#/Db6", filePath: "/audio/rhodes/85.m4a" },
            { midiNumber: 86, noteName: "D6", filePath: "/audio/rhodes/86.m4a" },
            { midiNumber: 87, noteName: "D#/Eb6", filePath: "/audio/rhodes/87.m4a" },
            { midiNumber: 88, noteName: "E6", filePath: "/audio/rhodes/88.m4a" },
            { midiNumber: 89, noteName: "F6", filePath: "/audio/rhodes/89.m4a" },
            { midiNumber: 90, noteName: "F#/Gb6", filePath: "/audio/rhodes/90.m4a" },
            { midiNumber: 91, noteName: "G6", filePath: "/audio/rhodes/91.m4a" },
            { midiNumber: 92, noteName: "G#/Ab6", filePath: "/audio/rhodes/92.m4a" },
            { midiNumber: 93, noteName: "A6", filePath: "/audio/rhodes/93.m4a" },
            { midiNumber: 94, noteName: "A#/Bb6", filePath: "/audio/rhodes/94.m4a" },
            { midiNumber: 95, noteName: "B6", filePath: "/audio/rhodes/95.m4a" },
            { midiNumber: 96, noteName: "C7", filePath: "/audio/rhodes/96.m4a" },
            { midiNumber: 97, noteName: "C#/Db7", filePath: "/audio/rhodes/97.m4a" },
            { midiNumber: 98, noteName: "D7", filePath: "/audio/rhodes/98.m4a" },
            { midiNumber: 99, noteName: "D#/Eb7", filePath: "/audio/rhodes/99.m4a" },
            { midiNumber: 100, noteName: "E7", filePath: "/audio/rhodes/100.m4a" },
            { midiNumber: 101, noteName: "F7", filePath: "/audio/rhodes/101.m4a" },
            { midiNumber: 102, noteName: "F#/Gb7", filePath: "/audio/rhodes/102.m4a" },
            { midiNumber: 103, noteName: "G7", filePath: "/audio/rhodes/103.m4a" }
        ]
    }
]
