export const cadencePatterns = [
    { type: "Major", pattern: [[62, 65, 69, 72], [62, 65, 67, 71], [60, 64, 67, 71]] },
    { type: "Minor", pattern: [[62, 65, 68, 72], [62, 65, 67, 71], [60, 63, 67, 72]] },
    { type: "Major Chromatic", pattern: [[2, 5, 9, 12], [2, 5, 7, 11], [0, 4, 7, 11]] },
    { type: "Minor Chromatic", pattern: [[2, 5, 8, 12], [2, 5, 7, 11], [0, 3, 7, 12]] }
]

export const scalePatterns = [
    { type: "Chromatic", pattern: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1] },
    { type: "Major", pattern: [2, 2, 1, 2, 2, 2, 1] },
    { type: "Minor", pattern: [2, 1, 2, 2, 1, 2, 2] },
    { type: "Harm Min", pattern: [2, 1, 2, 2, 1, 3, 1] },
    { type: "Mel Min", pattern: [2, 1, 2, 2, 2, 2, 1] },
    { type: "Dor", pattern: [2, 1, 2, 2, 2, 1, 2] },
    { type: "Mixo", pattern: [2, 2, 1, 2, 2, 1, 2] },
    { type: "Ahava Raba", pattern: [3, 2, 2, 3, 2] },
    { type: "Altered", pattern: [1, 2, 1, 2, 2, 2, 2] },
    { type: "Lyd Dom", pattern: [2, 2, 2, 1, 2, 2, 1] },
    { type: "Locrian", pattern: [1, 2, 2, 1, 2, 2, 2] }
]

export const instruments = [
    {
        instrumentName: "Piano",
        instrumentSounds: [
            { midiNumber: 36, noteName: "C2", filePath: "/audio/piano/36.wav" },
            { midiNumber: 37, noteName: "C#/Db2", filePath: "/audio/piano/37.wav" },
            { midiNumber: 38, noteName: "D2", filePath: "/audio/piano/38.wav" },
            { midiNumber: 39, noteName: "D#/Eb2", filePath: "/audio/piano/39.wav" },
            { midiNumber: 40, noteName: "E2", filePath: "/audio/piano/40.wav" },
            { midiNumber: 41, noteName: "F2", filePath: "/audio/piano/41.wav" },
            { midiNumber: 42, noteName: "F#/Gb2", filePath: "/audio/piano/42.wav" },
            { midiNumber: 43, noteName: "G2", filePath: "/audio/piano/43.wav" },
            { midiNumber: 44, noteName: "G#/Ab2", filePath: "/audio/piano/44.wav" },
            { midiNumber: 45, noteName: "A2", filePath: "/audio/piano/45.wav" },
            { midiNumber: 46, noteName: "A#/Bb2", filePath: "/audio/piano/46.wav" },
            { midiNumber: 47, noteName: "B2", filePath: "/audio/piano/47.wav" },
            { midiNumber: 48, noteName: "C3", filePath: "/audio/piano/48.wav" },
            { midiNumber: 49, noteName: "C#/Db3", filePath: "/audio/piano/49.wav" },
            { midiNumber: 50, noteName: "D3", filePath: "/audio/piano/50.wav" },
            { midiNumber: 51, noteName: "D#/Eb3", filePath: "/audio/piano/51.wav" },
            { midiNumber: 52, noteName: "E3", filePath: "/audio/piano/52.wav" },
            { midiNumber: 53, noteName: "F3", filePath: "/audio/piano/53.wav" },
            { midiNumber: 54, noteName: "F#/Gb3", filePath: "/audio/piano/54.wav" },
            { midiNumber: 55, noteName: "G3", filePath: "/audio/piano/55.wav" },
            { midiNumber: 56, noteName: "G#/Ab3", filePath: "/audio/piano/56.wav" },
            { midiNumber: 57, noteName: "A3", filePath: "/audio/piano/57.wav" },
            { midiNumber: 58, noteName: "A#/Bb3", filePath: "/audio/piano/58.wav" },
            { midiNumber: 59, noteName: "B3", filePath: "/audio/piano/59.wav" },
            { midiNumber: 60, noteName: "C4", filePath: "/audio/piano/60.wav" },
            { midiNumber: 61, noteName: "C#/Db4", filePath: "/audio/piano/61.wav" },
            { midiNumber: 62, noteName: "D4", filePath: "/audio/piano/62.wav" },
            { midiNumber: 63, noteName: "D#/Eb4", filePath: "/audio/piano/63.wav" },
            { midiNumber: 64, noteName: "E4", filePath: "/audio/piano/64.wav" },
            { midiNumber: 65, noteName: "F4", filePath: "/audio/piano/65.wav" },
            { midiNumber: 66, noteName: "F#/Gb4", filePath: "/audio/piano/66.wav" },
            { midiNumber: 67, noteName: "G4", filePath: "/audio/piano/67.wav" },
            { midiNumber: 68, noteName: "G#/Ab4", filePath: "/audio/piano/68.wav" },
            { midiNumber: 69, noteName: "A4", filePath: "/audio/piano/69.wav" },
            { midiNumber: 70, noteName: "A#/Bb4", filePath: "/audio/piano/70.wav" },
            { midiNumber: 71, noteName: "B4", filePath: "/audio/piano/71.wav" },
            { midiNumber: 72, noteName: "C5", filePath: "/audio/piano/72.wav" },
            { midiNumber: 73, noteName: "C#/Db5", filePath: "/audio/piano/73.wav" },
            { midiNumber: 74, noteName: "D5", filePath: "/audio/piano/74.wav" },
            { midiNumber: 75, noteName: "D#/Eb5", filePath: "/audio/piano/75.wav" },
            { midiNumber: 76, noteName: "E5", filePath: "/audio/piano/76.wav" },
            { midiNumber: 77, noteName: "F5", filePath: "/audio/piano/77.wav" },
            { midiNumber: 78, noteName: "F#/Gb5", filePath: "/audio/piano/78.wav" },
            { midiNumber: 79, noteName: "G5", filePath: "/audio/piano/79.wav" },
            { midiNumber: 80, noteName: "G#/Ab5", filePath: "/audio/piano/80.wav" },
            { midiNumber: 81, noteName: "A5", filePath: "/audio/piano/81.wav" },
            { midiNumber: 82, noteName: "A#/Bb5", filePath: "/audio/piano/82.wav" },
            { midiNumber: 83, noteName: "B5", filePath: "/audio/piano/83.wav" },
            { midiNumber: 84, noteName: "C6", filePath: "/audio/piano/84.wav" },
            { midiNumber: 85, noteName: "C#/Db6", filePath: "/audio/piano/85.wav" },
            { midiNumber: 86, noteName: "D6", filePath: "/audio/piano/86.wav" },
            { midiNumber: 87, noteName: "D#/Eb6", filePath: "/audio/piano/87.wav" },
            { midiNumber: 88, noteName: "E6", filePath: "/audio/piano/88.wav" },
            { midiNumber: 89, noteName: "F6", filePath: "/audio/piano/89.wav" },
            { midiNumber: 90, noteName: "F#/Gb6", filePath: "/audio/piano/90.wav" },
            { midiNumber: 91, noteName: "G6", filePath: "/audio/piano/91.wav" },
            { midiNumber: 92, noteName: "G#/Ab6", filePath: "/audio/piano/92.wav" },
            { midiNumber: 93, noteName: "A6", filePath: "/audio/piano/93.wav" },
            { midiNumber: 94, noteName: "A#/Bb6", filePath: "/audio/piano/94.wav" },
            { midiNumber: 95, noteName: "B6", filePath: "/audio/piano/95.wav" },
            { midiNumber: 96, noteName: "C7", filePath: "/audio/piano/96.wav" },
            { midiNumber: 97, noteName: "C#/Db7", filePath: "/audio/piano/97.wav" },
            { midiNumber: 98, noteName: "D7", filePath: "/audio/piano/98.wav" },
            { midiNumber: 99, noteName: "D#/Eb7", filePath: "/audio/piano/99.wav" },
            { midiNumber: 100, noteName: "E7", filePath: "/audio/piano/100.wav" },
            { midiNumber: 101, noteName: "F7", filePath: "/audio/piano/101.wav" },
            { midiNumber: 102, noteName: "F#/Gb7", filePath: "/audio/piano/102.wav" },
            { midiNumber: 103, noteName: "G7", filePath: "/audio/piano/103.wav" }
        ]
    },
    {
        instrumentName: "Rhodes",
        instrumentSounds: [
            { midiNumber: 36, filePath: "/audio/rhodes/36.wav" },
            { midiNumber: 37, filePath: "/audio/rhodes/37.wav" },
            { midiNumber: 38, filePath: "/audio/rhodes/38.wav" },
            { midiNumber: 39, filePath: "/audio/rhodes/39.wav" },
            { midiNumber: 40, filePath: "/audio/rhodes/40.wav" },
            { midiNumber: 41, filePath: "/audio/rhodes/41.wav" },
            { midiNumber: 42, filePath: "/audio/rhodes/42.wav" },
            { midiNumber: 43, filePath: "/audio/rhodes/43.wav" },
            { midiNumber: 44, filePath: "/audio/rhodes/44.wav" },
            { midiNumber: 45, filePath: "/audio/rhodes/45.wav" },
            { midiNumber: 46, filePath: "/audio/rhodes/46.wav" },
            { midiNumber: 47, filePath: "/audio/rhodes/47.wav" },
            { midiNumber: 48, filePath: "/audio/rhodes/48.wav" },
            { midiNumber: 49, filePath: "/audio/rhodes/49.wav" },
            { midiNumber: 50, filePath: "/audio/rhodes/50.wav" },
            { midiNumber: 51, filePath: "/audio/rhodes/51.wav" },
            { midiNumber: 52, filePath: "/audio/rhodes/52.wav" },
            { midiNumber: 53, filePath: "/audio/rhodes/53.wav" },
            { midiNumber: 54, filePath: "/audio/rhodes/54.wav" },
            { midiNumber: 55, filePath: "/audio/rhodes/55.wav" },
            { midiNumber: 56, filePath: "/audio/rhodes/56.wav" },
            { midiNumber: 57, filePath: "/audio/rhodes/57.wav" },
            { midiNumber: 58, filePath: "/audio/rhodes/58.wav" },
            { midiNumber: 59, filePath: "/audio/rhodes/59.wav" },
            { midiNumber: 60, filePath: "/audio/rhodes/60.wav" },
            { midiNumber: 61, filePath: "/audio/rhodes/61.wav" },
            { midiNumber: 62, filePath: "/audio/rhodes/62.wav" },
            { midiNumber: 63, filePath: "/audio/rhodes/63.wav" },
            { midiNumber: 64, filePath: "/audio/rhodes/64.wav" },
            { midiNumber: 65, filePath: "/audio/rhodes/65.wav" },
            { midiNumber: 66, filePath: "/audio/rhodes/66.wav" },
            { midiNumber: 67, filePath: "/audio/rhodes/67.wav" },
            { midiNumber: 68, filePath: "/audio/rhodes/68.wav" },
            { midiNumber: 69, filePath: "/audio/rhodes/69.wav" },
            { midiNumber: 70, filePath: "/audio/rhodes/70.wav" },
            { midiNumber: 71, filePath: "/audio/rhodes/71.wav" },
            { midiNumber: 72, filePath: "/audio/rhodes/72.wav" },
            { midiNumber: 73, filePath: "/audio/rhodes/73.wav" },
            { midiNumber: 74, filePath: "/audio/rhodes/74.wav" },
            { midiNumber: 75, filePath: "/audio/rhodes/75.wav" },
            { midiNumber: 76, filePath: "/audio/rhodes/76.wav" },
            { midiNumber: 77, filePath: "/audio/rhodes/77.wav" },
            { midiNumber: 78, filePath: "/audio/rhodes/78.wav" },
            { midiNumber: 79, filePath: "/audio/rhodes/79.wav" },
            { midiNumber: 80, filePath: "/audio/rhodes/80.wav" },
            { midiNumber: 81, filePath: "/audio/rhodes/81.wav" },
            { midiNumber: 82, filePath: "/audio/rhodes/82.wav" },
            { midiNumber: 83, filePath: "/audio/rhodes/83.wav" },
            { midiNumber: 84, filePath: "/audio/rhodes/84.wav" },
            { midiNumber: 85, filePath: "/audio/rhodes/85.wav" },
            { midiNumber: 86, filePath: "/audio/rhodes/86.wav" },
            { midiNumber: 87, filePath: "/audio/rhodes/87.wav" },
            { midiNumber: 88, filePath: "/audio/rhodes/88.wav" },
            { midiNumber: 89, filePath: "/audio/rhodes/89.wav" },
            { midiNumber: 90, filePath: "/audio/rhodes/90.wav" },
            { midiNumber: 91, filePath: "/audio/rhodes/91.wav" },
            { midiNumber: 92, filePath: "/audio/rhodes/92.wav" },
            { midiNumber: 93, filePath: "/audio/rhodes/93.wav" },
            { midiNumber: 94, filePath: "/audio/rhodes/94.wav" },
            { midiNumber: 95, filePath: "/audio/rhodes/95.wav" },
            { midiNumber: 96, filePath: "/audio/rhodes/96.wav" },
            { midiNumber: 97, filePath: "/audio/rhodes/97.wav" },
            { midiNumber: 98, filePath: "/audio/rhodes/98.wav" },
            { midiNumber: 99, filePath: "/audio/rhodes/99.wav" },
            { midiNumber: 100, filePath: "/audio/rhodes/100.wav" },
            { midiNumber: 101, filePath: "/audio/rhodes/101.wav" },
            { midiNumber: 102, filePath: "/audio/rhodes/102.wav" },
            { midiNumber: 103, filePath: "/audio/rhodes/103.wav" }
        ]
    }
]
